import * as Yup from "yup";
export function initialValues() {
  return {
    tipoEvento: "",
    comentarios: "",
    kilometraje: "",
    ubicacion: "",
    combustible: "",
    facturacionFlete: "",
    pagoServicios: "",
    llanta: "",
    costoTotalRepuesto: "",
    repuesto: "",
    costoMantenimiento: "",
    costo: 0,
    userType: "",
    photoAssetURL: "",
    placa: "",
    //Adicional
    tipoGasto: "",
    numeroFactura: "",
    guiaRemitente: "",
    guiTransportista: "",
    carroceria: "",
    cantidad: 0,
    unidadMedida: "",
    tipoCarga: "",
    descripcionGasto: "",
    puntoInicio: "",
    puntoLlegada: "",
    clienteRUC: "",
    clienteNombre: "",
    moneda: "",
    //Datos Adicionales para Firebase
    fechaPostFormato: "",
    fechaPostISO: "",
    fotoPrincipal: "",
    createdAt: "",
    LastEventPosted: "",
    photoProfileURL: "",
    emailPerfil: "",
    emailCompany: "",
    nombrePerfil: "",
    nombreAsset: "",
    companyName: "",
    idFirebaseAsset: "",
    idEventFirebase: "",
    fechaContable: "",
    //pago conductor
    pagoConductor: 0,
    nombreConductor: "",
    tipoComprobante: "",
    tipoMantto: "",
    precioUnitario: 0,
    facturaPagada: "",
    fechadePago: "",
    enViaje: "",
    igv: 0,
    // pdf
    pdfFile: "",
    FilenameTitle: "",
    pdfPrincipal: "",
    pdfFile2: "",
    FilenameTitle2: "",
    pdfPrincipal2: "",
    //
    fechadeEmisionFactura: "",
    LavadoyEngrase: "",
  };
}
export function validationSchema() {
  return Yup.object({
    // tipoEvento: Yup.string().required("Campo obligatorio"),
    // ubicacion: Yup.object().required("Campo obligatorio"),
  });
}
