export const Item = {
  asset: "01-Freightliner",
  reporte: "Reporte de Mantenimiento",
  conductor: "Gregorio Cruz Soncco",
  empresa: "Maxnicol",
  imagen: require("../assets/assetpics/freight01.jpeg"),
  perfil: require("../assets/pictures/Elvis_Cruz_Formal.jpg"),
  fecha: "07 ene 2024 13:27 Hrs",
  titulo: "Falla en el motor",
  descripcion: "Falla en el motor, se recomienda cambiarlo por uno nuevo",
  AvanceEjecucion: 100,
  AvanceProyected: 100,
  Asset: "01-Freightliner",
  companyName: "Maxnicol",
  emailPerfil: "elviscruz45@gmail.com",
  Monto: 100,
  Moneda: "USD",
  FechaInicio: { seconds: 1630489200, nanoseconds: 0 },
  createdAt: { seconds: 1630489200, nanoseconds: 0 },
  HorasHombre: 100,
};
