export const tipoGasto = [
  { value: "Tipo de Ingreso", disabled: true },
  { value: "Facturacion" },
  { value: "Tipo de Gasto", disabled: true },
  { value: "Acces segurida y Epp" },
  { value: "Activos" },
  { value: "Afp" },
  { value: "Agua" },
  { value: "Alimentación ope" },
  { value: "Alimentación adm" },
  { value: "Alojamiento pais" },
  { value: "Alq equipos para oficina" },
  { value: "Alq equipos de computo" },
  { value: "Alquiler de almacen" },
  { value: "Alquiler auto" },
  { value: "Alquiler de bienes diversos" },
  { value: "Alquiler montacarga grua para almacen" },
  { value: "Alquiler oficina" },
  { value: "Amortizac. Software" },
  { value: "Arbitrio municipal" },
  { value: "Asesoria seguridad" },
  { value: "Asignacion familiar" },
  { value: "Asignacion por movilidad" },
  { value: "Asist y aten personal" },
  { value: "Atencion medica pers" },
  { value: "Avisos/publ diarios" },
  { value: "Balanza" },
  { value: "Bonificacion extraordinaria ley 29351" },
  { value: "Bonificacion e incentivos" },
  { value: "Capacitacion" },
  { value: "Cochera" },
  { value: "Combustible ope" },
  { value: "Combustible adm" },
  { value: "Courier y correspondencia" },
  { value: "Cts empleados" },
  { value: "Cuadrilla trans loc" },
  { value: "Cuadrilla trans inter" },
  { value: "Depreciacion edific.y construcciones leasing" },
  { value: "Depreciacion edificios y otras construcciones" },
  { value: "Depreciacion equipo computo" },
  { value: "Depreciacion equipos diversos" },
  { value: "Depreciacion equipos diversos leasing" },
  { value: "Depreciacion maquinaria y equipo" },
  { value: "Depreciacion maquinaria y equipo leasing" },
  { value: "Depreciacion muebles y enseres" },
  { value: "Depreciacion unidades de transporte" },
  { value: "Distribucion local" },
  { value: "Distribucion provincias" },
  { value: "Documentos operativos" },
  { value: "Donaciones" },
  { value: "Eliminacion de desechos" },
  { value: "Energia electrica" },
  { value: "Enlace a la red ipv" },
  { value: "Enlaces data center" },
  { value: "Fletes en aduanas" },
  { value: "Fletes interprovincial" },
  { value: "Fletes local" },
  { value: "Fletes otros" },
  { value: "Fumigacion y desinfeccion" },
  { value: "Gas natural" },
  { value: "Gastos notarialesy registrales" },
  { value: "Gastos bancarios" },
  { value: "Gastos no deducibles" },
  { value: "Gastos por penalidades" },
  { value: "Gps" },
  { value: "Gratificacion ordinarias" },
  { value: "Gratificaciones extraordinarias" },
  { value: "Gastos refrigerios" },
  { value: "Honor asesoria contable" },
  { value: "Honor asesoria especializada" },
  { value: "Honor asesoria operativo" },
  { value: "Honorarios abogados" },
  { value: "Impresos" },
  { value: "Impuesto vehicular" },
  { value: "Indemnizacion por cese empleados" },
  { value: "Indemnizacion vacacional" },
  { value: "Internet" },
  { value: "Lavado" },
  { value: "Licencia de software" },
  { value: "Lubricantes" },
  { value: "Manipuleo en almacen" },
  { value: "Mant correctivo vehiculos" },
  { value: "Mant de sist eléc" },
  { value: "Mant equipos de manipuleo" },
  { value: "Mant equipos de computo" },
  { value: "Mant equipos diversos" },
  { value: "Mant licencia software" },
  { value: "Mant llantas" },
  { value: "Mant preventivo vehiculos" },
  { value: "Mant sistema seguridad" },
  { value: "Mant y rep edificacion" },
  { value: "Merchandising" },
  { value: "Movilidades" },
  { value: "Muebles y enseres" },
  { value: "Nivelado y toldeo" },
  { value: "Otras cargas diversas" },
  { value: "Otras cargas de pers" },
  { value: "Otros alquileres" },
  { value: "Otros gastos de inversion" },
  { value: "Otros gtos marketing" },
  { value: "Pasajes pais" },
  { value: "Peaje y estacionamiento" },
  { value: "Refrigerio" },
  { value: "Sanciones administrat fiscales" },
  { value: "Sanciones administrativas" },
  { value: "Sctr" },
  { value: "Seg particular eps" },
  { value: "Seguro asistencia medica" },
  { value: "Seguro complement. Trabajo de riesgo" },
  { value: "Seguro de vida" },
  { value: "Seguro social empleados" },
  { value: "Seguro vehiculos /poliza" },
  { value: "Seleccion de personal" },
  { value: "Servicio de mensajeria" },
  { value: "Servicio de vigilancia" },
  { value: "Servicios de limpieza" },
  { value: "Servicios terceros sistemas" },
  { value: "Soat" },
  { value: "Subvencion practicas pre-profesionales" },
  { value: "Sueldos basicos" },
  { value: "Sueldos horas extras" },
  { value: "Sueldos horas extras seguridad" },
  { value: "Suministros de computo" },
  { value: "Suministros diversos preventivo" },
  { value: "Suministros infraest" },
  { value: "Suministros llantas" },
  { value: "Suministros operativos" },
  { value: "Suministros operativos correctivo" },
  { value: "Suscripciones" },
  { value: "Telefonia fija" },
  { value: "Telefonia movil" },
  { value: "Tramites x ing pers" },
  { value: "Transp mov personal" },
  { value: "Uniformes personal" },
  { value: "Utiles de limpieza" },
  { value: "Utiles oficina y escritorio" },
  { value: "Vacaciones" },
];
