export const unidadesMedidaList = [
  { value: "Unidad" },
  { value: "Kilogramo" },
  { value: "Caja" },
  { value: "Paquete" },
  { value: "Toneladas" },
  { value: "Balde" },
  { value: "Barriles" },
  { value: "Bobinas" },
  { value: "Bolsa" },
  { value: "Botellas" },
  { value: "Cartones" },
  { value: "Centimetro cuadrado" },
  { value: "Centimetro cubico" },
  { value: "Centimetro lineal" },
  { value: "Ciento de unidades" },
  { value: "Cilindro" },
  { value: "Conos" },
  { value: "Docena" },
  { value: "Docena por 10**6" },
  { value: "Fardo" },
  { value: "Galon ingles (4,545956 l)" },
  { value: "Gramo" },
  { value: "Gruesa" },
  { value: "Hectolitro" },
  { value: "Hoja" },
  { value: "Juego" },
  { value: "Kilometro" },
  { value: "Kilovatio hora" },
  { value: "Kit" },
  { value: "Latas" },
  { value: "Libras" },
  { value: "Litro" },
  { value: "Megawatt hora" },
  { value: "Metro" },
  { value: "Metro cuadrado" },
  { value: "Metro cubico" },
  { value: "Miligramos" },
  { value: "Mililitro" },
  { value: "Milimetro" },
  { value: "Milimetro cuadrado" },
  { value: "Milimetro cubico" },
  { value: "Millares" },
  { value: "Millon de unidades" },
  { value: "Onzas" },
  { value: "Paletas" },
  { value: "Par" },
  { value: "Pie tablar" },
  { value: "Pies" },
  { value: "Pies cuadrados" },
  { value: "Pies cubicos" },
  { value: "Piezas" },
  { value: "Placas" },
  { value: "Pliego" },
  { value: "Pulgadas" },
  { value: "Resma" },
  { value: "Tambor" },
  { value: "Tonelada corta" },
  { value: "Tonelada larga" },
  { value: "Tubos" },
  { value: "Unidad" },
  { value: "Us galon (3,7843 l)" },
  { value: "Yarda" },
  { value: "Yarda cuadrada" },
];
